### ISSUE TITLE
Weapon reloading bug when the "clip_size" is changed

### ISSUE THREAD

**Issue by BioHazardN7** [SilvDev/Mission_and_Weapons-Info_Editor#1]
If the "clip_size" is changed and not full, the reload animation proceeds correctly. But if you try to reload a full magazine, a bug occurs.
[Video demonstration](https://drive.google.com/file/d/13M68WvkuXGllepTwEMHcYchpZ234HEF4/view)

**Comment by SilvDev** [comment]
I wrote this plugin to fix the issue: [Reload Fix - Max Clip Size](https://forums.alliedmods.net/showthread.php?t=327105)
